server:
  port: ${APP_PORT:8091}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_HOST:localhost}:${DB_PG_PORT:5432}/${DB_PG_BASE:jms-pay-db}
    username: ${DB_PG_USR_RW:postgres}
    password: ${DB_PG_PWD_RW:postgres}
  flyway:
    user: ${DB_PG_USR_MIGRATION:postgres}
    password: ${DB_PG_PWD_MIGRATION:postgres}
    url: jdbc:postgresql://${DB_PG_HOST:localhost}:${DB_PG_PORT:5432}/${DB_PG_BASE:jms-goods-db}
    baseline-on-migrate: true