server:
  port: ${APP_PORT:8092}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_HOST:localhost}:${DB_PG_PORT:5432}/${DB_PG_BASE:jms-notify-db}
    username: ${DB_PG_USR_RW:postgres}
    password: ${DB_PG_PWD_RW:postgres}
  flyway:
    user: ${DB_PG_USR_MIGRATION:postgres}
    password: ${DB_PG_PWD_MIGRATION:postgres}
    url: jdbc:postgresql://${DB_PG_HOST:localhost}:${DB_PG_PORT:5432}/${DB_PG_BASE:jms-notify-db}
    baseline-on-migrate: true
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES:localhost:5672}
    username: ${RABBITMQ_USR:jms-user}
    password: ${RABBITMQ_PWD:jms-user}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:jms}
rabbitmq:
  notify-exchange: ${NOTIFY_EXCHANGE:jms-wrk}
  notify-queue: ${NOTIFY_QUEUE:jms-notify}